
const langToggle = document.getElementById('lang-toggle');

const translations = {
     BN: {
          'brand-name': 'আইনপ্রো',
          'nav-home': 'হোম',
          'nav-features': 'বৈশিষ্ট্য',
          'nav-about': 'আমাদের সম্পর্কে',
          'nav-contact': 'যোগাযোগ',
          'nav-register': 'রেজিস্টার',
          'nav-login': 'লগইন',
          'hero-title': 'আইন পেশার ডিজিটাল ভবিষ্যৎ',
          'hero-subtitle': 'আপনার আইনি ব্যবস্থাপনাকে সহজ ও দ্রুত করুন।',
          'hero-cta': 'বৈশিষ্ট্য দেখুন',
          'features-title': 'শক্তিশালী বৈশিষ্ট্য',
          'feature1-title': 'অ্যাকাউন্ট তৈরি করুন',
          'feature1-text': 'আইনজীবীরা সহজেই তাদের নাম, যোগাযোগ, ইমেল এবং পাসওয়ার্ড দিয়ে অ্যাকাউন্ট তৈরি করতে পারেন।',
          'feature2-title': 'সহজে লগইন করুন',
          'feature2-text': 'নিবন্ধিত ইমেল এবং পাসওয়ার্ড ব্যবহার করে ড্যাশবোর্ডে দ্রুত প্রবেশ করুন।',
          'feature3-title': 'ক্লায়েন্ট ব্যবস্থাপনা',
          'feature3-text': 'ক্লায়েন্টদের তথ্য, মামলা অবস্থা এবং ইতিহাস এক জায়গায় রাখুন।',
          'feature4-title': 'দ্রুত ড্যাশবোর্ড',
          'feature4-text': 'মোট ক্লায়েন্ট, সক্রিয় মামলা এবং মামলা অগ্রগতি এক নজরে দেখুন।',
          'feature5-title': 'মামলার বিস্তারিত',
          'feature5-text': 'মামলার নম্বর, ক্লায়েন্ট, আদালত এবং স্ট্যাটাস আপডেট সহ সম্পূর্ণ তথ্য পান।',
          'feature6-title': 'শুনানির রেকর্ড',
          'feature6-text': 'আদালতের তারিখ, মন্তব্য এবং ফলাফল ট্র্যাক করুন। রিপোর্ট প্রিন্ট বা ডাউনলোড করুন।',
          'feature7-title': 'মামলা শ্রেণীবিন্যাস',
          'feature7-text': 'দ্রুত প্রবেশের জন্য মামলা নাগরিক, পরিবার বা ফৌজদারি বিভাগে ভাগ করুন।',
          'feature8-title': 'আদালত ব্যবস্থাপনা',
          'feature8-text': 'আপনার অঞ্চলের ভিত্তিতে সুপ্রিম কোর্ট বা হাই কোর্টের নাম যোগ, সম্পাদনা বা মুছুন।',
          'feature9-title': 'নোটিসেস',
          'feature9-text': 'মহৎ মামলা নোটিস এবং রিমাইন্ডার সরাসরি সিস্টেমে পান।',
          'feature10-title': 'অ্যাপয়েন্টমেন্ট',
          'feature10-text': 'ক্লায়েন্ট অ্যাপয়েন্টমেন্ট নির্ধারণ ও পরিচালনা করুন সহজেই।',
          'feature11-title': 'ক্যালেন্ডার ইন্টিগ্রেশন',
          'feature11-text': 'আপনার সকল শুনানি ও অ্যাপয়েন্টমেন্ট ক্যালেন্ডারের সাথে সিঙ্ক করুন।',
          'feature12-title': 'ডকুমেন্ট ম্যানেজমেন্ট',
          'feature12-text': 'মামলা সম্পর্কিত সকল ডকুমেন্ট সুরক্ষিতভাবে সংরক্ষণ ও পরিচালনা করুন।',
          'about-title': 'LCMS সম্পর্কে',
          'about-text': 'লইয়ার কেস ম্যানেজমেন্ট সিস্টেম আইনজীবী এবং ফার্মদের জন্য কেস পরিচালনা সহজ করে।',
          'contact-title': 'যোগাযোগ করুন',
          'contact-subtitle': 'প্রশ্ন, প্রতিক্রিয়া বা সহায়তার জন্য আমাদের মেসেজ পাঠান।',
          'contact-form-title': 'মেসেজ পাঠান',
          'label-name': 'আপনার নাম',
          'label-email': 'আপনার ইমেল',
          'label-subject': 'বিষয়',
          'label-message': 'আপনার বার্তা',
          'contact-btn': 'পাঠান',
          'contact-info-title': 'যোগাযোগের তথ্য',
          'info-address-title': 'ঠিকানা',
          'info-address-text': 'মিরপুর-১০, ঢাকা, বাংলাদেশ',
          'info-email-title': 'ইমেল',
          'info-email-text': 'info@lawyercasepro.com',
          'info-phone-title': 'ফোন',
          'info-phone-text': '+৮৮০ ১২৩ ৪৫৬৭৮৯',
          'footer-brand': 'আইনপ্রো',
          'footer-contact': 'যোগাযোগ: info@lawyercasepro.com | +৮৮০ ১২৩ ৪৫৬৭৮৯'
     },
     EN: {
          'brand-name': 'LawyerCasePro',
          'nav-home': 'Home',
          'nav-features': 'Features',
          'nav-about': 'About',
          'nav-contact': 'Contact',
          'nav-register': 'Register',
          'nav-login': 'Login',
          'hero-title': 'Manage Cases Smarter with LCMS',
          'hero-subtitle': 'Simplify your legal workflow with an all-in-one case management system built for modern lawyers.',
          'hero-cta': 'Explore Features',
          'features-title': 'Powerful Features',
          'feature1-title': 'Get Your Account',
          'feature1-text': 'Lawyers can easily create accounts by providing their name, contact details, email, and a secure password.',
          'feature2-title': 'Log In Easily',
          'feature2-text': 'Access your dashboard quickly using your registered email and password.',
          'feature3-title': 'Client Management',
          'feature3-text': 'Keep track of all your clients’ details — contact info, case status, and history — in one place.',
          'feature4-title': 'Quick Dashboard',
          'feature4-text': 'View all your important stats at a glance — total clients, active cases, and case progress.',
          'feature5-title': 'Case Details',
          'feature5-text': 'Access complete case information including case numbers, clients, courts, and status updates.',
          'feature6-title': 'Hearing Records',
          'feature6-text': 'Track court hearing dates, remarks, and outcomes. Print or download reports easily.',
          'feature7-title': 'Categorize Cases',
          'feature7-text': 'Organize cases into categories like Civil, Family, or Criminal for quick access.',
          'feature8-title': 'Court Management',
          'feature8-text': 'Add, edit, or remove court names such as Supreme Court or High Court based on your jurisdiction.',
          'feature9-title': 'Notices',
          'feature9-text': 'Receive important case notices and reminders directly within the system.',
          'feature10-title': 'Appointments',
          'feature10-text': 'Schedule and manage client appointments efficiently with notifications.',
          'feature11-title': 'Calendar Integration',
          'feature11-text': 'Sync all case hearings and appointments with your calendar for easy tracking.',
          'feature12-title': 'Document Management',
          'feature12-text': 'Store, organize, and manage all case-related documents securely in one place.',
          'about-title': 'About LCMS',
          'about-text': 'The Lawyer Case Management System helps advocates and law firms handle cases effortlessly. From managing clients and hearings to generating reports — LCMS makes legal work smoother and more organized.',
          'contact-title': 'Get in Touch',
          'contact-subtitle': 'Have questions, feedback, or need assistance? Send us a message — we’d love to hear from you.',
          'contact-form-title': 'Send a Message',
          'label-name': 'Full Name',
          'label-email': 'Email Address',
          'label-subject': 'Subject',
          'label-message': 'Message',
          'contact-btn': 'Send Message',
          'contact-info-title': 'Contact Information',
          'info-address-title': 'Address',
          'info-address-text': 'Mirpur-10, Dhaka, Bangladesh',
          'info-email-title': 'Email',
          'info-email-text': 'info@lawyercasepro.com',
          'info-phone-title': 'Phone',
          'info-phone-text': '+880 123 456789',
          'footer-brand': 'LawyerCasePro',
          'footer-contact': 'Contact: info@lawyercasepro.com | +880 123 456789'
     }
};

langToggle.addEventListener('click', () => {
     const currentLang = langToggle.innerText;
     const newLang = currentLang === 'EN' ? 'BN' : 'EN';
     langToggle.innerText = newLang;

     Object.keys(translations[newLang]).forEach(id => {
          const el = document.getElementById(id);
          if (el) el.innerText = translations[newLang][id];
     });
});

